//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KineskaHrana.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogadjaji
    {
        public int idDogadjaj { get; set; }
        public string dogadjaj_opis { get; set; }
        public int id_korisnik { get; set; }
        public System.DateTime vreme { get; set; }
    }
}
