//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KineskaHrana.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public int idKontakt { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string poruka { get; set; }
        public string email { get; set; }
    }
}
