//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KineskaHrana.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meni
    {
        public int idMeni { get; set; }
        public string naziv_meni { get; set; }
        public string link_meni { get; set; }
        public int prioritet_meni { get; set; }
    }
}
