//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KineskaHrana.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbine
    {
        public int idNarudzbina { get; set; }
        public int idKorisnik { get; set; }
        public int idJelo { get; set; }
        public System.DateTime vreme { get; set; }
        public decimal cena { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string adresa { get; set; }
    }
}
