//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KineskaHrana.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovori
    {
        public int idOdgovor { get; set; }
        public string odgovor { get; set; }
        public int idAnketa { get; set; }
        public int brojGlasova { get; set; }
    }
}
